# Is not recommended to have this file in the project directory
# Only used for make easier the build of the Docker compose file
dbt_adworks:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port:  5432
      dbname: postgres
      schema: dbo